name: Deploy to EC2

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - main
    
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -l ec2-user ${{ secrets.EC2_HOST }} <<-EOF
          cd /home/ec2-user/TaskWeb-Backend
          git pull
          mkdir example
        EOF