name: Deploy to EC2 and Change Tracking New Relic

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - main
    
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -l ec2-user ${{ secrets.EC2_HOST }} <<-EOF
          cd /home/ec2-user/TaskWeb-Backend
          git pull
          sudo systemctl restart taskweb-backend.service
        EOF
  
  newrelic:
    runs-on: ubuntu-latest

    steps:
    - name: Set Release Version from Tag
      run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: New Relic Application Deployment Marker
      uses: newrelic/deployment-marker-action@v2.3.0
      with:
        apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
        guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
        version: "${{ env.RELEASE_VERSION }}"
        user: "${{ github.actor }}"
        region: "EU"

